spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: yoonjulie1*
  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: tester
      password: password